# Generated by Django 2.2 on 2020-01-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200115_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Books'), (2, 'Movies')]),
        ),
    ]
